### ISSUE TITLE
Question: Is libpfc code C89

### ISSUE THREAD

**Issue by travisdowns** [obilaniu/libpfc#11]
I saw you made a change to make the code compile under C89. Is that the general policy for `libpfc`? In that case I'll update the makefile to set it to compile in C89 which will catch those issues in the future. Personally I recommend no earlier than C99 as a reasonable baseline that almost is likely to have a compiler for.

**Comment by obilaniu** [comment]
It's not a general policy, but the Meson build on my machine with the system GCC (4.8.5) failed because that version still assumes C89. I thought that fix was relatively simple so I did it.

But frankly, this kernel module probably only works only relatively recent kernels, and the oldest GCC still allowed to compile the kernel probably supported C99 for ages. I'll look at modifying the default Meson so it asks for C99.

Let's pretend the C standard to follow here is *C99*.

**Comment by obilaniu** [comment]
@travisdowns To make this more precise, Linus Torvalds has [an ambivalent attitude to it](https://stackoverflow.com/questions/20600497/which-c-version-is-used-in-the-linux-kernel), but the kernel code is generally C89 with occasional use of C99 features. The `Makefile` I'm using for kernel module compilation already uses the default arguments for the kernel (and those are C89).

But the userland code I don't mind being solid C99.

**Comment by travisdowns** [comment]
Cool. To be clear, it seems like we are using at least some "gnu" extensions (e.g., `asm` among other things) so I set the standard to `-std=gnu99` in the makefile and that seems to work.

**Comment by obilaniu** [comment]
@travisdowns Yeah for my part I just added `gnu99` to `meson.build`. We should both be able to work in C99 for userland code now.

**Comment by travisdowns** [comment]
I have added `-std=gnu99` to `Makefile` in the pending pull request.
