### ISSUE TITLE
Overhead and latency of libpfc

### ISSUE THREAD

**Issue by bgin** [obilaniu/libpfc#26]
Hello,

I'm interested in latency measurement in TSC cycles (presumably returned by the RDTSCP instruction) of whole back-to-back overhead of  following functions
pfcWrCfgs(0, 7,      CFG);
pfcWrCnts(0, 7, ZERO_CNT);
PFCSTART(b)
PFCEND(b)

By crude observation the overhead in cycles of whole macro execution may be circa 27-30 cycles multiplied by 7 counter accesses.

**Comment by obilaniu** [comment]
This is the purpose of the call to [`pfcRemoveBias(CNT, k);`](https://github.com/obilaniu/libpfc/blob/master/src/pfcdemo.c#L170). It executes a "negative" version of `PFCSTART()` and `PFCEND()` to estimate the overhead of those macros for the current counters, and subtracts `k` multiples of them out of `CNT`.

**Comment by bgin** [comment]
Thank you for your answer.

I have an additional question.

Can I specify so called event modifiers and pass it  to pfcParseCfg function?
I'm interested in:  user/kernel mode counting, the period (sample after value), any thread, cmask, edge detection and invert flag?
What is the syntax of those event modifiers?
Can I use a SEP event modifiers syntax (as described below)
https://software.intel.com/content/www/us/en/develop/download/sep-user-guide.html

**Comment by obilaniu** [comment]
The function `pfcParseCfg()` is implemented [here](https://github.com/obilaniu/libpfc/blob/master/src/libpfc.c#L493). It's not very well documented, but the syntax is *not* exactly like the GNU `perf` tool or anything else. It's more like, in order:

- `[*]` An optional flag indicating edge triggering.
- `eventName/number` Name or number of an event name.
- `.`
- `umaskName/number` Name of number of an event subname/umask
- `[{<,>=}cmask]` Optional `cmask` value, with `<` or `>=` determining invert flag.
- `[:[AaUuKk]*]` Separator for flags, plus any combination Anythread (`Aa`), Usermode (`Uu`), Os/Kernelmode (`Kk`).

This felt more logical and powerful to me than the `perf` syntax, although it has some similarities (like `:u`). In particular, the various combinations of edge-trigger/cmask/invert modes are not encoded in the umask name, but are separate syntactical elements. For the anythread/user/kernel modes I mimicked `perf` because I was quite content with that syntax.

But truthfully, my code uses a table of event names I scraped together from various sources for Haswell CPUs, and these counters may not have the same meaning for newer CPUs, or be supported on them, and there's definitely things missing from newer CPUs like Skylake. I only have a Haswell processor, which is why I baked those values in.

Furthermore, I was unable to find a way, for example, to make accumulated counter values and configurations "follow" a thread being migrated from core to core, which is why the `pfcPinThread()` function exists. The only way to do that appears to be to hack the Linux kernel itself, or use its perf subsystem, but it seems impossible to ask that subsystem to position a particular event on a particular counter, nor does it seem possible to query what decision did the kernel eventually take with respect to such positioning. The only way that the perf API allows associating the raw performance counters with the metrics requested is via a system call to query the values - but that's a heavy-weight operation, certainly much heavier than my lightweight `asm` `PFCSTART`/`PFCEND` macros that yank out the counter values with a few tens of clock cycles of overhead.

This codebase should be considered mostly a fragile Haswell toy codebase, and it might be easier to get GNU `perf` to work for getting access to newer counters or full codebases. I use this library primarily for microarchitectural benchmarking and tuning of small chunks of single-threaded code like inner-most loops.

**Comment by bgin** [comment]
Thank you for your lengthy response.
The syntax explanation solved a lot of headache.

I was aware of Haswell only limitation by reading various opened issues.
I have also a Haswell CPU so it may be working.

I was looking for a low latency programmable performance counters access tool or better a library, which will enable a precise loop/function instrumentation, but will not be restricted to fixed counters.
I evaluated itt-notify and perf_event open mechanism, but those are long latency syscall based operation presumably lasting for 1000-2000 cycles and not very well suited for precise measurement or inner loop tuning. They may be good for huge iteration
of short loops where the execution steady-state was reached, not so helpful in case of  real-world scenario where instruction and data cache miss dominates at least at initial stages of execution.

Now in regards to  `asm PFCSTART/PFCEND ` macros as far as I know RDPMC can read programmable counters from the kernel space mode and you seems to me enabled the PCE bit in order to read those counters from the user space?
Intel description of RDPMC is quiet perplexing in case of GP exception.
The pseudo-code of RDPMC implementation says something different, that protected mode and 64-bit mode exception warning.
https://www.felixcloutier.com/x86/rdpmc

The whole perf and maybe VTune mechanism of access multiplexing, virtualization and thread following is very powerful, but at the large cost of latency and overhead of thousands of cycles and are not very helpful in precise measurement and loop tuning.

**Comment by obilaniu** [comment]
> Now in regards to `asm PFCSTART/PFCEND` macros as far as I know RDPMC can read programmable counters from the kernel space mode and you seems to me enabled the PCE bit in order to read those counters from the user space?

I ask people to execute as root `echo 2 > /sys/bus/event_source/devices/cpu/rdpmc` to do this. I seem to recall having trouble invoking the equivalent kernel function from a module. Yes, the desired end-result is that `rdpmc` should be accessible from userspace.

The fact that you have a Haswell processor and you need to do very low-latency measurements means you might be one of the rare people to benefit from this particular package. I can certainly try to support you.

**Comment by obilaniu** [comment]
Another thing: Nobody is actually obliged to use `pfcParseCfg()`. The register configuration values it produces can be computed ahead of time manually, and a more flexible library like [libpfm](http://perfmon2.sourceforge.net/manv4/pfm_find_event.html), of which I was entirely unaware when I wrote this library, can also convert textual string descriptions to configurations. That library appears to support a wider range of processors than merely Haswell, and my Linux kernel module, shaky as it is, might actually stand a chance of running on newer processors as well.

One thing to note though; Some events can only be configured on certain counters. For instance, IIRC, L1 cache misses can only be measured on programmable counter `1`, not `0` or `2` or `3`. I don't think I check against this anywhere, but I was mindful of this when actually using my code. In the 7-element array of configs and counts, elements 0-2 correspond to the fixed-function counters, and 3-6 correspond to the programmable counters 0-3 respectively. There is no attempt at shuffling counters' order to make sure more, or all, constraints are satisfied, for the sake of simplicity.

**Comment by bgin** [comment]
> The fact that you have a Haswell processor and you need to do very low-latency measurements means you might be one of the rare people to benefit from this particular package. I can certainly try to support you.

Sorry for long delay.

Thank you very much for your help.
I definitely plan to test "libpfc", but I'm not interested in micro-benchmarking anymore.
Low-latency access methods in my case may be a vital in measuring a computational kernels and other HPC code.
I'm also interested in profiling huge HPC applications like written in Fortran e.g. WRF model, by performing a first measurement sweep with VTune locating various function-level and loop-level hotspots and inserting a wrapper calls to PFCSTART/PFCEND macros (defined as simple functions) callable from Fortran.

Soon I plan to acquire a new machine possibly an Ice-Lake or Cascade-Lake SP based server or workstation and this will require an extensive testing of "libpfc".

> Nobody is actually obliged to use pfcParseCfg(). The register configuration values it produces can be computed ahead of time manually, and a more flexible library like libpfm, of which I was entirely unaware when I wrote this library, can also convert textual string descriptions to configurations. That library appears to support a wider range of processors than merely Haswell, and my Linux kernel module, shaky as it is, might actually stand a chance of running on newer processors as well.

Yes I have that library also.
I also came across John D. McCalpin "low-overhead-timers" short library (rather a few functions mainly RDPMC based) for reading PMCs from the user mode.
His approach claims up to 24 cycles of overhead, but relies on manual masks creation for PerfEventSelx registers and setting them by the means of msr-tools.
His methods was extensively tested on SKX first and second generation servers and suits my needs very well.
Please have a look:
https://github.com/jdmccalpin/low-overhead-timers
